### ISSUE TITLE
Documentation without complete information

### ISSUE THREAD

**Issue by theinem** [blue-yonder/tsfresh#824] opened 2021-03-13 20:33 UTC
-  The data on which the problem occurred: is related to the documentation

Hi. I was reading the documentation from my Mozilla web browser, I have taken screenshots of sections in the documentation that, I think, are incomplete.

![imagen](https://user-images.githubusercontent.com/18086414/111043628-7f4d1280-8411-11eb-968c-4b16e18be260.png)

**Comment by nils-braun** [comment] 2021-03-20 09:52
Thanks for the issue @theinem! That one is a duplicate of #810 - so I am closing this one (for some house keeping). If you know a nice solution to this or would like to help, we would be very happy!

**Closed by nils-braun** 2021-03-20 09:52 UTC
