### ISSUE TITLE
Deprecation warnings with Pandas with pandas.core.datetools

### ISSUE THREAD

**Issue by junhaobearxiong** [blue-yonder/tsfresh#355] opened 2018-01-21 16:55 UTC
from tsfresh import feature_extraction

When executing the above code, I got the following warning:

/Users/junhaoxiong/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

I have just install tsfresh. The pandas version I am using is 0.20.3. 

Any help would be appreciated!

**Comment by MaxBenChrist** [comment] 2018-02-04 23:55
duplicate of #282

**Closed by MaxBenChrist** 2018-02-04 23:55 UTC
