### ISSUE TITLE
pandas.core.datetools deprecation error

### ISSUE THREAD

**Issue by rgalbo** [blue-yonder/tsfresh#282] opened 2017-08-02 14:15 UTC
When you import `extract_features` from `tsfresh` this deprecation warning is given, I can't find where this is imported in the package. 

![pandas core error](https://user-images.githubusercontent.com/6351996/28877790-0e23342c-7763-11e7-9d33-5b695492acdd.JPG)

**Comment by nils-braun** [comment] 2017-08-02 14:17
Yes, this is correct - I have also seen this warning. The problem is, as you have stated, that we are not importing this in our own code - but some library we use imports this.
If I find the time, I will track this down and see, if we can make a PR to this external library.
Thank you for reporting this!

**Comment by MaxBenChrist** [comment] 2017-08-02 14:19
That warning is from statsmodels.

**Comment by nils-braun** [comment] 2017-08-02 14:22
Ok, thanks @MaxBenChrist :-)

**Comment by nils-braun** [comment] 2017-08-02 14:27
And it was fixed on #3618 in statsmodels - but only on master not in any release they have, as far as I see.

So the only possibility is to import this with disabled warnings...

**Closed** 2018-09-10 18:40 UTC
