### ISSUE TITLE
MaybeEncodingError: Error sending result

### ISSUE THREAD

**Issue by florianhumblot** [blue-yonder/tsfresh#604] opened 2019-11-26 15:17 UTC
OS: Win 10 64-bit build 1903
TSFresh version: 0.12.0
The data: A Dataframe consisting of time series data, expanded by `tsfresh.utilities.dataframe_functions.roll_time_series` with a `max_timeshift` of 4.
This results in a dataframe with the following shape: `(1106660, 6)`

When calling `tsfresh.extract_relevant_features` with the following parameters:
```
extract_relevant_features(
          rolled, y, column_id='id', column_value='y1', column_sort='x',
          chunksize=1)
```

I receive the following error:
` MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x03EF7670>'. Reason: 'PicklingError("Can't pickle <class 'MemoryError'>: it's not the same object as builtins.MemoryError")' `

With the following stacktrace:

```

---------------------------------------------------------------------------
MaybeEncodingError                        Traceback (most recent call last)
<ipython-input-19-ab006a0111f4> in <module>
      7 rolled_features = extract_relevant_features(
      8          rolled, y, column_id='id', column_value='y1', column_sort='x',
----> 9          chunksize=1)
     10 # rolled_features=pd.DataFrame(rolled_features)
     11 print(rolled_features.shape)

c:\users\fhumblot\appdata\local\programs\python\python37-32\lib\site-packages\tsfresh\convenience\relevant_extraction.py in extract_relevant_features(timeseries_container, y, X, default_fc_parameters, kind_to_fc_parameters, column_id, column_sort, column_kind, column_value, show_warnings, disable_progressbar, profile, profiling_filename, profiling_sorting, test_for_binary_target_binary_feature, test_for_binary_target_real_feature, test_for_real_target_binary_feature, test_for_real_target_real_feature, fdr_level, hypotheses_independent, n_jobs, chunksize, ml_task)
    162                              column_id=column_id, column_sort=column_sort,
    163                              column_kind=column_kind, column_value=column_value,
--> 164                              impute_function=impute)
    165 
    166     X_sel = select_features(X_ext, y,

c:\users\fhumblot\appdata\local\programs\python\python37-32\lib\site-packages\tsfresh\feature_extraction\extraction.py in extract_features(timeseries_container, default_fc_parameters, kind_to_fc_parameters, column_id, column_sort, column_kind, column_value, chunksize, n_jobs, show_warnings, disable_progressbar, impute_function, profile, profiling_filename, profiling_sorting, distributor)
    176                                 default_fc_parameters=default_fc_parameters,
    177                                 kind_to_fc_parameters=kind_to_fc_parameters,
--> 178                                 distributor=distributor)
    179 
    180         # Impute the result if requested

c:\users\fhumblot\appdata\local\programs\python\python37-32\lib\site-packages\tsfresh\feature_extraction\extraction.py in _do_extraction(df, column_id, column_value, column_kind, default_fc_parameters, kind_to_fc_parameters, n_jobs, chunk_size, disable_progressbar, distributor)
    321     result = distributor.map_reduce(_do_extraction_on_chunk, data=data_in_chunks,
    322                                     chunk_size=chunk_size,
--> 323                                     function_kwargs=kwargs)
    324     distributor.close()
    325 

c:\users\fhumblot\appdata\local\programs\python\python37-32\lib\site-packages\tsfresh\utilities\distribution.py in map_reduce(self, map_function, data, function_kwargs, chunk_size, data_length)
    147             result = self.distribute(_function_with_partly_reduce, chunk_generator, map_kwargs),
    148 
--> 149         result = list(itertools.chain.from_iterable(result))
    150 
    151         return result

c:\users\fhumblot\appdata\local\programs\python\python37-32\lib\site-packages\tqdm\std.py in __iter__(self)
   1089             """), fp_write=getattr(self.fp, 'write', sys.stderr.write))
   1090 
-> 1091         for obj in iterable:
   1092             yield obj
   1093             # Update and possibly print the progressbar.

c:\users\fhumblot\appdata\local\programs\python\python37-32\lib\multiprocessing\pool.py in next(self, timeout)
    746         if success:
    747             return value
--> 748         raise value
    749 
    750     __next__ = next                    # XXX

MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x03EF7670>'. Reason: 'PicklingError("Can't pickle <class 'MemoryError'>: it's not the same object as builtins.MemoryError")'

```

I obviously have a MemoryError but it isn't reported like usual because of the multiprocessing I guess. 

(side note, isn't chunksize supposed to "solve" the memory issues by splitting the extraction and selection of features by series?)

**Comment by dbarbier** [comment] 2019-11-26 16:12
> (side note, isn't chunksize supposed to "solve" the memory issues by splitting the extraction and selection of features by series?)

No, chunksize does almost nothing w.r.t. memory, it is there only to try to balance load between workers; in order for multiprocessing to be efficient, each worker must have a reasonable amount of work, so we want a large chunksize.  On the other hand if it is too large, some workers could sleep.

Here your dataframe has a shape `(1106660, 6)`; tsfresh will compute features for 6 timeseries (of size 1106660, which is huge).  In fact, you likely want to cut your timeseries into many small pieces with `make_forecasting_frame`, as in  https://github.com/blue-yonder/tsfresh/blob/5bb37fbd/notebooks/timeseries_forecasting_basic_example.ipynb

**Comment by florianhumblot** [comment] 2019-11-27 07:33
> tsfresh will compute features for 6 timeseries (of size 1106660, which is huge).
As far as I can tell by the output of `extract_relevant_features` it's actually extracting the features of about 110 features that each have (about) 10k points each. 

Thanks for the explanation on `chunksize`, I must have misunderstood it when I was reading the docs.

**Comment by dbarbier** [comment] 2019-11-27 10:07
> As far as I can tell by the output of extract_relevant_features it's actually extracting the features of about 110 features that each have (about) 10k points each.

Okay, then I misunderstood your original figures.  You have 10k distinct ids, and each timeseries have a length around 100.  This should not cause memory issues.

There have been several reports about warnings and multiprocessing on Windows, I wonder whether those warnings could take lots of RAM.  This has to be investigated, maybe try to add in your script

```python
import logging
logging.getLogger("tsfresh.feature_selection.relevance").setLevel(logging.ERROR)
logging.getLogger("tsfresh.feature_selection.significance_tests").setLevel(logging.ERROR)
logging.getLogger("tsfresh.utilities.dataframe_functions").setLevel(logging.ERROR)
```

Of course I do not recommend to turn off warnings like this, this is just some debugging stuff to try to find the root cause of your problems.

**Comment by nils-braun** [comment] 2020-04-11 10:00
I assume that helped (or at least you could solve the issue differently). If not, in my recent blog post I described how to use `tsfresh` with `dask`, `spark` or how to do this splitting using a task orchestrator such as `luigi`. Maybe this helps! https://nils-braun.github.io/tsfresh-on-cluster-2/
I am closing now - if you have more problems please reopen!

**Closed by nils-braun** 2020-04-11 10:00 UTC
