### ISSUE TITLE
ValueError: Expected 2D array, got 1D array instead - Example Notebook

### ISSUE THREAD

**Issue by seb-koch** [blue-yonder/tsfresh#351] opened 2017-11-15 15:44 UTC
Hi,

i just tried tsfresh on a fresh Anaconda Installation on Mac OSX and used the timeseries_forecasting_google_stock.ipyn example Notebook.

It fails at row 15 with the error
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-20-4ace78a2ebb6> in <module>()
      9     ada.fit(X.iloc[:i], y[:i])
     10 #    y_pred[i] = ada.predict([X.iloc[i, :]])[0]
---> 11     y_pred[i] = ada.predict(X.iloc[i, :])[0]
     12 
     13 y_pred = pd.Series(data=y_pred, index=y.index)

/Users/sebastiankoch/anaconda2/lib/python2.7/site-packages/sklearn/ensemble/weight_boosting.pyc in predict(self, X)
   1092         """
   1093         check_is_fitted(self, "estimator_weights_")
-> 1094         X = self._validate_X_predict(X)
   1095 
   1096         return self._get_median_predict(X, len(self.estimators_))

/Users/sebastiankoch/anaconda2/lib/python2.7/site-packages/sklearn/ensemble/weight_boosting.pyc in _validate_X_predict(self, X)
    267                 isinstance(self.base_estimator,
    268                            (BaseDecisionTree, BaseForest))):
--> 269             X = check_array(X, accept_sparse='csr', dtype=DTYPE)
    270 
    271         else:

/Users/sebastiankoch/anaconda2/lib/python2.7/site-packages/sklearn/utils/validation.pyc in check_array(array, accept_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, warn_on_dtype, estimator)
    439                     "Reshape your data either using array.reshape(-1, 1) if "
    440                     "your data has a single feature or array.reshape(1, -1) "
--> 441                     "if it contains a single sample.".format(array))
    442             array = np.atleast_2d(array)
    443             # To ensure that array flags are maintained

ValueError: Expected 2D array, got 1D array instead:
array=[  2.73839819e+03   2.17000008e+00  -5.78064978e-01  -1.90940484e-01
   1.04077208e+00   1.27399998e+01  -1.00000000e+00  -1.05999994e+00
   1.25360003e+01  -9.28982794e-01  -4.28999990e-01   1.20859422e-01
   1.19740000e+01  -1.00000000e+00  -5.59000015e-01   1.21406002e+01
  -9.73261118e-01  -2.97399998e-01   4.96318452e-02   1.15500002e+01
  -1.00000000e+00  -3.00000012e-01   1.17309999e+01  -9.92145598e-01
  -1.69000000e-01   1.50665194e-02   1.40003994e-01  -1.00000000e+00
  -1.19079001e-01   1.05885603e-01  -7.97514617e-01  -4.26784009e-02
   2.28290353e-02   8.78050104e-02   2.82984734e-01   1.52189299e-01
   1.56389520e-01   1.20526582e-01   4.39043373e-01   7.36399889e-01
   7.51484931e-01  -2.52870113e-01   2.12263852e-01   9.58532095e-01
  -0.00000000e+00   9.00000000e+00   1.00000000e+00   7.53945112e-01
   5.43398380e-01   3.00419897e-01   1.95989057e-01   1.37017697e-01
   6.54645488e-02   1.19634286e-01   3.14595178e-02  -4.54372764e-02
   1.68657005e+00   1.59049915e+03   1.58404053e+03   1.58444885e+03
  -1.49999997e-02  -3.28571424e-02  -5.99999987e-02  -4.89999987e-02
  -7.59999976e-02  -5.00000007e-02  -3.33333351e-02  -3.90000008e-02
  -1.57142859e-02  -1.49999997e-02  -7.84210563e-02  -9.85714272e-02
  -1.00000001e-01  -1.70000002e-01  -3.03333342e-01   3.50000001e-02
   5.57142869e-02   7.99999982e-02   6.49999976e-02   8.39999989e-02
   5.00000007e-02   7.86666647e-02   9.49999988e-02   9.00000036e-02
   2.50000004e-02   1.14210524e-01   1.38571426e-01   1.47272721e-01
   1.73333332e-01   3.03333342e-01   1.22500001e-03   3.47755104e-03
   6.39999984e-03   3.86899989e-03   4.38399985e-03   9.99999975e-05
   1.03155551e-02   1.44290002e-02   1.60244890e-02   6.24999986e-04
   2.06554011e-02   2.58122440e-02   3.10727265e-02   2.76999995e-02
   1.84888896e-02   2.24999996e-04   1.45306124e-03   3.59999994e-03
   2.04499997e-03   3.10399989e-03   9.99999975e-05   5.23822242e-03
   6.92499988e-03   8.17142893e-03   2.24999996e-04   1.37612186e-02
   1.63265299e-02   1.93834715e-02   2.65555549e-02   1.84888896e-02
   7.13652551e-01   1.79207480e+00   9.00000000e+00   1.10000000e+01
   2.01707020e+01   5.94560325e-01   2.05496445e+01   6.95893717e+00
   3.87651329e+01   2.17523545e-01   3.99989090e+01   1.20150309e+01
   3.83975182e+01   1.55353114e-01   3.82509689e+01   1.39570694e+01
   3.76498489e+01   6.86396286e-02   3.64187202e+01   1.59131231e+01
   3.64996452e+01   5.06236069e-02   3.45004311e+01   1.76508980e+01
   3.49365730e+01   3.14630836e-01   3.25454369e+01   1.88273296e+01
   2.33920288e+01   7.62986517e+00   2.28188705e+01   1.15364723e+01
   2.64958878e+01   9.90687084e+00   2.50616436e+01   1.54939661e+01
   2.93880634e+01   7.47113705e+00   2.72446651e+01   1.84305534e+01
   3.19852104e+01   3.65227175e+00   2.93740673e+01   2.00884075e+01
   3.42183495e+01   1.02462637e+00   3.14131660e+01   2.04786396e+01
   3.60339508e+01  -1.55506367e-02   3.33579178e+01   1.97617321e+01
   3.74001236e+01  -1.33400276e-01   3.52064400e+01   1.82210350e+01
   3.83040848e+01   4.21167016e-02   3.69322777e+01   1.62190456e+01
   3.87513885e+01   1.89557806e-01   3.85359230e+01   1.40632420e+01
   1.16238639e-01   1.06533550e-01   1.00920342e-01   9.95627642e-02
   1.00834563e-01   9.92960036e-02   9.64214727e-02   9.38379541e-02
   9.35075432e-02   9.28471610e-02   2.48223156e-01   3.83732948e+01
   5.80202770e+00   1.43365812e+00   2.33889999e+02   2.33889999e+02
   6.89999998e-01   0.00000000e+00   6.89999998e-01   3.31997013e+00
  -6.00626373e+01  -2.87699127e+00   1.65684080e+00   2.95101786e+00
  -3.60117912e+01  -1.73505604e+00   2.38706660e+00   2.14152122e+00
  -5.65263405e+01  -1.78632736e+00   1.18116379e+00   1.42606735e+00
  -5.53045578e+01  -1.17249739e+00   8.11737597e-01   1.28082001e+00
  -4.72147560e+01  -9.39999998e-01   8.70000005e-01   9.51942205e-01
  -4.75154572e+01  -7.02018917e-01   6.42933488e-01   3.96621644e-01
  -1.03540444e+00  -7.16704549e-03   3.96556884e-01   9.71613109e-01
  -4.75976658e+00  -8.06225911e-02   9.68262374e-01   1.21670747e+00
  -1.07288084e+01  -2.26503044e-01   1.19543850e+00   0.00000000e+00
   9.49999988e-01  -8.64124146e+02   2.03355057e+02  -1.60775108e+01
   4.49590087e-01   1.00000000e+00   0.00000000e+00   0.00000000e+00
   1.00000001e-01   2.00000003e-01   3.00000012e-01   4.00000006e-01
   6.00000024e-01   6.99999988e-01   8.00000012e-01   8.99999976e-01
   1.37096930e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
   1.00000000e+00   1.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   5.00000007e-02   1.00000000e+00
   2.00000000e+01   1.22744284e+01   2.36670090e-07  -8.83926213e-01
  -6.10451140e-02   7.61198020e-03   6.00000000e+00   1.00000000e+01
   1.37034121e+01   1.27399998e+01   1.16945000e+01   1.14210524e-01
  -7.84210563e-02   5.55555569e-03   1.16599998e+01   1.12500000e+01
   5.00000000e+00   2.00000000e+00   5.00000000e+00   1.00000000e+00
   0.00000000e+00   7.53945112e-01  -5.80092520e-02  -2.07625657e-01
   1.40999392e-01   4.02742438e-02  -1.45061582e-01   2.75456756e-01
  -2.99227118e-01  -1.41365096e-01   5.26315793e-02   1.00000001e-01
   1.12980003e+01   1.13420000e+01   1.14440002e+01   1.15299997e+01
   1.17440004e+01   1.17600002e+01   1.18059998e+01   1.23369999e+01
   5.00000000e-01   2.50000000e-01   1.50000006e-01   5.00000007e-02
   5.00000007e-02   0.00000000e+00   9.49999988e-01   1.81303692e+00
   1.30279803e+00   8.62055942e-02   1.35737751e-03   2.06576381e-03
   3.98227006e-01   2.35200005e+01   1.17600002e+01   2.33889999e+02
   1.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
   1.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
   1.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
   1.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
   1.00000000e+00   1.00000000e+00   1.00000000e+00  -4.25299454e+01
  -7.35953674e+01  -9.91712265e+01   1.58584744e-01   1.12500000e+01].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
```

The error can be easily fixed by changing the predict call and enclose the passed array in brackets.
```
# Original call which throws the error
#        y_pred[i] = ada.predict(X.iloc[i, :])[0]
# adding brackets solves it
y_pred[i] = ada.predict([X.iloc[i, :]])[0]
```

I am a total tsfresh novice and a python beginner. I am not sure why this error happens and if it may be caused by some new versions of the sklearn library or because i am using python 2.7? Maybe you are already aware and it is an intended exception?

Same error comes up in the basic forecasting notebook too.

Regards,

**Comment by MaxBenChrist** [comment] 2018-02-05 00:06
Thanks for reporting @seb-koch,

the cleaner way would be to add braces around the `[i]`, because `X.iloc[[i], :]` returns a pandas DataFrame and not a Series.

**Comment by MaxBenChrist** [comment] 2018-02-05 00:07
Also, we need to up pandas-datareader to 0.6.0 because the url to parse the stock data changed.

**Comment by MaxBenChrist** [comment] 2018-09-04 18:13
This was fixed in #427

**Closed by MaxBenChrist** 2018-09-04 18:13 UTC

**Comment by ishriana** [comment] 2021-06-30 09:25
Hi Max, i have tried running your suggestions but things dint work. Could you please assist me with this error.
https://github.com/ishriana/Assignments.git. Error is in A6.ipynb

**Comment by nils-braun** [comment] 2021-06-30 19:02
Hi @ishriana - please note that your error occurs with the `sklearn` package (more detailed, with the `LinearRegression` class).
This issue tracker is for the `tsfresh` python package (which is unrelated, the error listed above is similar, but only occurs because tsfresh is using sklearn internally).

I think you will get a lot more help on the corresponding issue tracker for [sklearn ](https://github.com/scikit-learn/scikit-learn/issues) (maybe try searching for a similar issue first) or on stackoverfow. Actually, there are already some answers to a [very similar question](https://stackoverflow.com/questions/51150153/valueerror-expected-2d-array-got-1d-array-instead) which you should check out first.
