### ISSUE TITLE
Index of X and y must be identical if provided

### ISSUE THREAD

**Issue by AASHISHAG** [blue-yonder/tsfresh#601] opened 2019-11-22 11:36 UTC
Hello, 

First of all, congratulations and thank you for the great work. 

I am trying to use tsfresh to extract features on weather data.  I followed the documentation but got stuck with the error.

OS: Ubuntu 16.04
Tsfresh: Latest

```
import pandas as pd
from tsfresh import select_features
from tsfresh import extract_features
from tsfresh.utilities.dataframe_functions import impute

df = pd.read_csv('pre_processed_data.csv')
df.head()
df_X = df.iloc[:,0:15]
df_y = df.iloc[:,15]

extracted_features = extract_features(df_X, column_id="id")
impute(extracted_features)
features_filtered = select_features(extracted_features, df_y)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "agarwal/python-environments/sah/lib/python3.5/site-packages/tsfresh/feature_selection/selection.py", line 140, in select_features
    raise ValueError("Index of X and y must be identical if provided")
ValueError: Index of X and y must be identical if provided


>>> extracted_features.shape
(1999, 11116)
>>> df_X.shape
(1999, 15)
```

data: https://github.com/AASHISHAG/time-series-classification/blob/master/pre_processed_data.csv

The number of rows in my X (features) and Y (class) are equal. Am I making some mistake? Please advise.

**Comment by dbarbier** [comment] 2019-11-22 12:58
Hello, `select_features` docstring contains:

    The target vector must be a pandas.Series or numpy.array in the form

        +-------+--------+
        | index | target |
        +=======+========+
        | A     | ...    |
        +-------+--------+
        | B     | ...    |
        +-------+--------+
        | .     | ...    |
        +-------+--------+
        | .     | ...    |
        +-------+--------+

    and must contain all id's that are in the feature matrix. If y is a numpy.array without
    index, it is assumed that y has the same order and length than X and the rows
    correspond to each other.

The problem here is that `extracted_features` index is `df_X.id` and not `df_X` index.
Either write `df_y = df.iloc[:,15].values` or set its index with `df_y.index = df_X.id`.

**Comment by AASHISHAG** [comment] 2019-11-24 14:58
Thank you, for the response.

It worked. But unfortunately `features_filtered` is empty. Did I miss anything?

**Comment by dbarbier** [comment] 2019-11-24 18:39
The problem is that your CSV file does not contain timeseries, see
https://tsfresh.readthedocs.io/en/latest/text/data_formats.html#input-option-1-flat-dataframe

**Comment by AASHISHAG** [comment] 2019-11-25 09:58
Does that mean I cannot use tsfresh? 

I don't have a time column in my CSV, as described in the above link you posted, because each column in the CSV corresponds to a particular day of the last 20 years or is there any other way? Please guide.

data: https://github.com/AASHISHAG/time-series-classification/blob/master/pre_processed_data.csv

**Comment by kempa-liehr** [comment] 2019-11-25 10:32
If you assume, that your target is influenced by past values (e.g. the last 30 days of `wind_max` or `wind_ave`), you can model your problem as time series forecasting https://tsfresh.readthedocs.io/en/latest/text/forecasting.html. 

In this case, column `id` would be the temporal dimension.

**Comment by AASHISHAG** [comment] 2019-12-14 13:21
@kempa-liehr : Thank you for your guidance. Yes, my target depends on the last 5 days. I tried the following, adding a rolling method, but I still got an empty data frame. Did I make any mistake? Kindly guide.


```
import pandas as pd
from tsfresh import select_features
from tsfresh import extract_features
from tsfresh.utilities.dataframe_functions import impute
from tsfresh.utilities.dataframe_functions import roll_time_series

df = pd.read_csv('pre_processed_data.csv')
df.head()
df_X = df.iloc[:,0:15]
df_y = df.iloc[:,15]

rolled = roll_time_series(df_X, column_id='id', column_kind=None, column_sort=None, rolling_direction=1, max_timeshift=5)
extracted_features = extract_features(rolled, column_id="id", impute_function=impute, show_warnings=False, n_jobs=56)
features_filtered = select_features(extracted_features, df_y.values)
```

**Comment by nils-braun** [comment] 2020-02-13 20:17
Do you have a good feeling on which features might be relevant for your target or is this basically a shot into the blue?
tsfresh uses a feature selection algorithm  based on statistical hypothesis tests. If none of your features are deemed relevant, they are removed. However, it is "just" a statistical hypothesis test and therefore not perfect. Domain knowledge would certainly help you to say if one of the features is clearly meaningful, so you could verify if tsfresh keeps it or not. 

Also, 15 rows is really not a lot. Did you try with more? As tsfresh uses statistical tests it will get better with more data :-)

**Comment by nils-braun** [comment] 2020-04-11 08:02
@AASHISHAG  I am closing this issue now as I assume the answers have helped you. If you still have the problem, please reopen this issue :-)

**Closed by nils-braun** 2020-04-11 08:02 UTC
