### ISSUE TITLE
problem in calculating index_mass

### ISSUE THREAD

**Issue by MoffyJiang** [blue-yonder/tsfresh#175] opened 2017-03-29 04:03 UTC
Hi, our company is trying to apply tsfresh on our credit scoring models for time series data but one problems came up.  During calculating index_mass, np.argmax(mass_centralized >= config["q"])+1) is trying to get the index of a time series for a single sample when the cumsum of this feature is greater than given quantile. however, the results is not a 'relative' index within a time series data for a single sample but relative to the index of the whole sample. 
For example, in the show case robot_execution_failures, extracted feature 'a__index_mass_quantile__q_0.1' increases when sample id increases. In my experience, using a pure random id to classify samples always has good statistical evaluation results but the models themselves are meaningless. 
We are thinking that is it a better way to reset dataframe index while calculating index mass? So that  the np.argmax will get the the index regardless of which part of the whole sample is the sample from  but just the position of the time in the series.

**Comment by MaxBenChrist** [comment] 2017-03-29 07:04
Hi @MoffyJiang 

may I ask why you closed this issue?

I think the point that you mentioned is valid. I will investigate this.

**Comment by MoffyJiang** [comment] 2017-03-29 07:13
Hi sorry I saw #162 and I thought it was the same issue as mine. But after I read it carefully I found that was about id not index....sorry

**Comment by MaxBenChrist** [comment] 2017-03-29 07:13
I now how to fix this. We can just call `.value` before `np.argmax`

Thanks for reporting, I will add a pr later.

**Comment by MoffyJiang** [comment] 2017-03-29 07:15
ah yes! thanks for your help!

**Comment by MaxBenChrist** [comment] 2017-03-29 07:28
#162 was about the id column but the behavior is caused by the index

**Comment by MaxBenChrist** [comment] 2017-03-29 11:57
Please check if your problems also occur with version 0.7.0, if they do reopen this issue. 

again, thanks for reporting this one

**Closed by MaxBenChrist** 2017-03-29 11:57 UTC

**Comment by MoffyJiang** [comment] 2017-03-29 11:59
thanks for your help!
