### ISSUE TITLE
Use tqdm for Jupyter Notebooks

### ISSUE THREAD

**Issue by anderl80** [blue-yonder/tsfresh#580] opened 2019-11-06 20:05 UTC
When using tsfresh in Jupyter Notebook, output from tqdm results bar is not overwriting itself but creating a line for every change in percentage. Can we somehow build a switch for using tqdm_notebook?

**Comment by rpanai** [comment] 2019-11-06 20:26
This seems to see a bug. Check this [issue](https://github.com/tqdm/tqdm/issues/375) out. It happens to me whenever I have to interrupt the kernel at some point. Do you mind to share a [mcve](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)?

**Comment by nils-braun** [comment] 2019-11-29 20:58
@anderl80 Reading what @rpanai has posted, I think we can close this issue. Correct?

**Comment by rjurney** [comment] 2019-12-04 06:44
Can someone pretty please fix this? It makes tqdm worse than worthless.

**Comment by dbarbier** [comment] 2019-12-04 11:20
No problem here with tqdm in Jupyter notebooks; do you reproduce this issue with very simple workflows, as in https://tsfresh.readthedocs.io/en/latest/text/quick_start.html ?

**Comment by dbarbier** [comment] 2019-12-04 11:28
And if you edit `tsfresh/utilities/distribution.py` and replace
```
from tqdm import tqdm
```
by
```
from tqdm.auto import tqdm
```
does it fix your issues?

**Comment by gunjan-solanki** [comment] 2019-12-18 05:46
It's an old issue with tqdm on jupyter . see here : https://github.com/tqdm/tqdm/issues/375

Workaround is to clear tqdm instance with  
```tqdm._instances.clear()```
whenever it occurs. 

https://github.com/tqdm/tqdm/issues/375#issuecomment-559578029

**Comment by dbarbier** [comment] 2019-12-18 08:37
Different workarounds have been suggested in this issue; il looks like main tqdm developer advocates importing `tqdm.auto`, thus it is a better option IMO if it works, this is why I requested feedback.

**Comment by nils-braun** [comment] 2019-12-19 19:03
The problem I have with the `tqdm.auto` is that you might fall into
```python
ImportError: IntProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
```
as we are note requiring ipywidgets.
What do people think?

**Comment by rjurney** [comment] 2019-12-19 19:51
This is a common enough problem that it seems like it should ‘just work’ in both a console and a Jupyter Notebook. People don’t always know the context in which their code will be run and requiring every library to determine its execution context and use a different API seems an enormous duplication of effort that could be done once by making the default method for tqdm work in both console and Jupyter.

Am I right?

**Comment by nils-braun** [comment] 2020-02-13 20:12
I am closing this issue as it has nothing to do with tsfresh, but is an upstream issue for tqdm (where it was addressed or at least discussed already).

**Comment by rjurney** [comment] 2020-02-14 01:33
@nils-braun this breaks your library on the most popular platform where it is used. This attitude is unfortunate and impacts many (most?) users of the library.

**Comment by MaxBenChrist** [comment] 2020-02-14 02:53
What about detecting the environment where tsfresh is run and use the respective Bar? See also https://stackoverflow.com/questions/15411967/how-can-i-check-if-code-is-executed-in-the-ipython-notebook

**Comment by nils-braun** [comment] 2020-02-14 06:32
@rjurney sorry did not want to be rude! :-)
I think then I misunderstood the problem. 

I thought it is a problem in the tqdm library (and if we can fix it there much more people can benefit from this) - but if course we can also do a workaround in tsfresh (which will obviously not fix the root cause). Do you already have a solution in mind and are you willing to do a PR with it? We are always happy for contributors!

**Comment by casperdcl** [comment] 2020-04-16 23:01
fixed in `tqdm>=4.45.0`, which should not require any special handling on exceptions (no need to catch and clear instances). If it does, please post on https://github.com/tqdm/tqdm/issues/548.

Also if you can't use `tqdm.auto.tqdm`/`tqdm.notebook.tqdm` and still have this issue even when no exceptions are triggered then it's probably just your env not supporting `\r`. https://github.com/tqdm/tqdm/#faq-and-known-issues

**Comment by casperdcl** [comment] 2020-04-16 23:06
btw @nils-braun the expected behaviour is:

```
from tqdm import tqdm  # plain-text version; relies on `\r`
from tqdm.notebook import tqdm  # notebook version; relies on ipywidgets
from tqdm.autonotebook import tqdm  # auto-detect frontend, printing warning
from tqdm.auto import tqdm  # auto-detect frontend, not printing warning
```

so basically `from tqdm.auto import tqdm` should fallback to just the plain-text version if `ipywidgets` is not found, without printing any warnings. Is this not the case?

**Comment by nils-braun** [comment] 2020-04-17 17:39
@casperdcl Thanks for the very nice update and thanks for reporting it here :-)
(by the way, thanks for the super nice library!) 
The `from tqdm.auto import tqdm` work as expected in console mode as well as in jupyter notebooks, as long as the `ipywidgets` package is installed. If it is not installed and you call it in a jupyter notebook, it will first fail with
```python
NameError: name 'IProgress' is not defined
```
and the error handling of that will fail in
```python
ImportError: FloatProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
```
I guess this is expected (from looking at your code you are trying out different combinations if `IPython.html.widgets` and `ipywidgets`) and you are printing a very nice error message, so in my opinion this is fine.

**Closed by nils-braun** 2020-04-17 17:39 UTC

**Comment by casperdcl** [comment] 2020-04-18 16:43
Hmm. I'm not sure about the case of running in a notebook sans `ipywidgets` when using `tqdm.auto`. Perhaps it's best to raise an `ImportWarning` and fallback to the CLI version rather than raising an `ImportError`?

**Comment by nils-braun** [comment] 2020-04-20 17:27
I guess it depends on what message you meant to communicate: is tqdm well tested and well working in CLI mode even in notebooks (e.g. no bugs like the one described here) or do you assume that notebooks work best with the widgets?
The former means more testing cases you need to cover and the latter means more restrictions for the users. 
(In my opinion tqdm looks really good with widgets :-))

**Comment by casperdcl** [comment] 2020-04-20 17:56
> is tqdm well tested and well working in CLI mode even in notebooks (e.g. no bugs like the one described here) or do you assume that notebooks work best with the widgets?

Both :)
