### ISSUE TITLE
Feature extraction problem

### ISSUE THREAD

**Issue by fereshtemohebbi** [blue-yonder/tsfresh#218] opened 2017-06-22 09:30 UTC
[merge-finger-012345.copy.xlsx](https://github.com/blue-yonder/tsfresh/files/1094386/merge-finger-012345.copy.xlsx)

[warning.docx](https://github.com/blue-yonder/tsfresh/files/1094258/warning.docx)

Hi 
I have two IMU sensor with
 100 hz data rate which I extract yaw pitch roll angle with each of them.I window finger movement with them and I need to extract and filter feature for that window.
as an Id I pick timestamp. I attached my data to show panda data frame. But the problem is that it shows that feature extraction is 100 percent but after warnings I dont have any feature to filter them. The problem is with the data ? thanks for your help

**Comment by nils-braun** [comment] 2017-06-22 14:13
Please send us a jupyter notebook or a pyton file with your data (or how you import it), and how you call tsfresh. Otherwise it is hard to reproduce the bug.

**Comment by fereshtemohebbi** [comment] 2017-06-22 14:26
[runscr.txt](https://github.com/blue-yonder/tsfresh/files/1095074/runscr.txt)
Sorry i want able to attach python file, I just attach the text that I run on my pc. And could please let me know that is my data correct for two sensor (I mean in one Id I use their data as kind ) because I need feature for the whole period  of one window( I determine them with window in kind) 
thanks for your kind help

**Comment by nils-braun** [comment] 2017-06-22 14:53
Which part of this exactly is not working? I have just tested the extraction (before the second excel file loading) with the first 100 IDs, but so far everything is fine. Are you sure this was not just a problem with to less memory or alike? Because your datasample is quite large.

**Comment by fereshtemohebbi** [comment] 2017-06-22 15:00
the problem is that it shows 100 percent feature extraction and all the warnings(I sent in warning.docs) but after that nothing will happen , no error , no feature 
Could please let me know in this situtation the way that I choose for feature extraction is correct or not? Do you have solution for me

**Comment by nils-braun** [comment] 2017-06-23 00:03
Your way of extraction is in principle correct.
Again, I have tested your code with the first 100 ids (because I do not have that much RAM), and it worked out well.
What do you mean with "no error, not feature"? Do you get back an empty dataframe? Or is the script just "hanging"? Because with your large dataset and small memory, this is what may happen.

**Comment by fereshtemohebbi** [comment] 2017-06-23 09:09
The thing is that I check this amount of data with just 2 ID (Logically is incorrect just for test) It works and i extract feature . Then I change the ID to the time stamp which it goes up and the script hangs just shows 100 percent feature extraction but hangs. So I have several question and confusion :+1: 
1) I am confused that tsfresh extract feature base on ID number ? 
2 ) I read the examples on tsfresh but in my situation and this limitation could you advise me about ID and kind how can I choose them to reduce the number of ID ?(I have large data set ,each second 100 sample for two sensor 
Thanks for your consideration

**Comment by nils-braun** [comment] 2017-06-25 14:58
To 1) Please read our documentation, where it this is described. Yes, the features are extracted for each ID separately (which makes sense of course)
To 2) You could for example just feed in the first 1/10 of the data, then the second etc. You just have to make sure to make "reasonable" cuts (e.g. have the data for a given ID in one partition).

I will close this issue now, as tsfresh runs well with your problem (there seems to be no bug in my eyes), you just have a memory problem. You could try with parallelisation disabled, but the problem is probably, that your full result dataframe does not fit into your memory.

If you still encounter a bug, please reopen this again or a new issue.

**Closed by nils-braun** 2017-06-25 14:58 UTC
