### ISSUE TITLE
LinkerError: [222] Call to cuLinkAddData results in UNKNOWN_CUDA_ERROR ptxas application ptx input, line 9; fatal   : Unsupported .version 7.5; current version is '7.2'

### ISSUE THREAD

**Issue by alekseikorobov** [blue-yonder/tsfresh#922] opened 2022-01-07 13:13 UTC
Hello!
When I include ```from tsfresh import extract_features``` I get Error:

```
---------------------------------------------------------------------------
CudaAPIError                              Traceback (most recent call last)
~/.virtualenvs/ml/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py in add_ptx(self, ptx, name)
   2187         try:
-> 2188             driver.cuLinkAddData(self.handle, enums.CU_JIT_INPUT_PTX,
   2189                                  ptxbuf, len(ptx), namebuf, 0, None, None)

~/.virtualenvs/ml/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py in safe_cuda_api_call(*args)
    302             retcode = libfn(*args)
--> 303             self._check_error(fname, retcode)
    304 

~/.virtualenvs/ml/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py in _check_error(self, fname, retcode)
    342                     raise CudaDriverError("CUDA initialized before forking")
--> 343             raise CudaAPIError(retcode, msg)
    344 

CudaAPIError: [222] Call to cuLinkAddData results in UNKNOWN_CUDA_ERROR

During handling of the above exception, another exception occurred:

LinkerError                               Traceback (most recent call last)
/tmp/ipykernel_17620/1575443908.py in <module>
----> 1 from tsfresh import extract_features

~/.virtualenvs/ml/lib/python3.8/site-packages/tsfresh/__init__.py in <module>
     25 
     26 
---> 27 from tsfresh.convenience.relevant_extraction import (  # noqa: E402
     28     extract_relevant_features,
     29 )

~/.virtualenvs/ml/lib/python3.8/site-packages/tsfresh/convenience/relevant_extraction.py in <module>
      6 
      7 from tsfresh import defaults
----> 8 from tsfresh.feature_extraction import extract_features
      9 from tsfresh.feature_selection import select_features
     10 from tsfresh.utilities.dataframe_functions import (

~/.virtualenvs/ml/lib/python3.8/site-packages/tsfresh/feature_extraction/__init__.py in <module>
      3 """
      4 
----> 5 from tsfresh.feature_extraction.extraction import extract_features
      6 from tsfresh.feature_extraction.settings import (
      7     ComprehensiveFCParameters,

~/.virtualenvs/ml/lib/python3.8/site-packages/tsfresh/feature_extraction/extraction.py in <module>
     13 
     14 from tsfresh import defaults
---> 15 from tsfresh.feature_extraction import feature_calculators
     16 from tsfresh.feature_extraction.data import to_tsdata
     17 from tsfresh.feature_extraction.settings import ComprehensiveFCParameters

~/.virtualenvs/ml/lib/python3.8/site-packages/tsfresh/feature_extraction/feature_calculators.py in <module>
     27 import numpy as np
     28 import pandas as pd
---> 29 import stumpy
     30 from matrixprofile.exceptions import NoSolutionPossible
     31 from numpy.linalg import LinAlgError

~/.virtualenvs/ml/lib/python3.8/site-packages/stumpy/__init__.py in <module>
     28 
     29 if cuda.is_available():
---> 30     from .gpu_stump import gpu_stump  # noqa: F401
     31     from .gpu_aamp import gpu_aamp  # noqa: F401
     32     from .gpu_ostinato import gpu_ostinato  # noqa: F401

~/.virtualenvs/ml/lib/python3.8/site-packages/stumpy/gpu_stump.py in <module>
     11 
     12 from . import core, config
---> 13 from .gpu_aamp import gpu_aamp
     14 
     15 logger = logging.getLogger(__name__)

~/.virtualenvs/ml/lib/python3.8/site-packages/stumpy/gpu_aamp.py in <module>
     19     "f8[:], f8[:], i8, b1, i8, f8[:, :], i8[:, :], b1)"
     20 )
---> 21 def _compute_and_update_PI_kernel(
     22     i,
     23     T_A,

~/.virtualenvs/ml/lib/python3.8/site-packages/numba/cuda/decorators.py in kernel_jit(func)
     99             targetoptions['opt'] = opt
    100             targetoptions['fastmath'] = fastmath
--> 101             return Dispatcher(func, [func_or_sig], targetoptions=targetoptions)
    102 
    103         def device_jit(func):

~/.virtualenvs/ml/lib/python3.8/site-packages/numba/cuda/compiler.py in __init__(self, py_func, sigs, targetoptions)
    934             if len(sigs) > 1:
    935                 raise TypeError("Only one signature supported at present")
--> 936             self.compile(sigs[0])
    937             self._can_compile = False
    938 

~/.virtualenvs/ml/lib/python3.8/site-packages/numba/cuda/compiler.py in compile(self, sig)
   1113             self.overloads[argtypes] = kernel
   1114 
-> 1115             kernel.bind()
   1116             self.sigs.append(sig)
   1117         return kernel

~/.virtualenvs/ml/lib/python3.8/site-packages/numba/cuda/compiler.py in bind(self)
    624         Force binding to current CUDA context
    625         """
--> 626         self._codelibrary.get_cufunc()
    627 
    628     @property

~/.virtualenvs/ml/lib/python3.8/site-packages/numba/cuda/codegen.py in get_cufunc(self)
    199             return cufunc
    200 
--> 201         cubin = self.get_cubin(cc=device.compute_capability)
    202         module = ctx.create_module_image(cubin)
    203 

~/.virtualenvs/ml/lib/python3.8/site-packages/numba/cuda/codegen.py in get_cubin(self, cc)
    172         ptxes = self._get_ptxes(cc=cc)
    173         for ptx in ptxes:
--> 174             linker.add_ptx(ptx.encode())
    175         for path in self._linking_files:
    176             linker.add_file_guess_ext(path)

~/.virtualenvs/ml/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py in add_ptx(self, ptx, name)
   2189                                  ptxbuf, len(ptx), namebuf, 0, None, None)
   2190         except CudaAPIError as e:
-> 2191             raise LinkerError("%s\n%s" % (e, self.error_log))
   2192 
   2193     def add_file(self, path, kind):

LinkerError: [222] Call to cuLinkAddData results in UNKNOWN_CUDA_ERROR
ptxas application ptx input, line 9; fatal   : Unsupported .version 7.5; current version is '7.2'
```

**Environment**:

- Python version: 3.8.10
- System:
NAME="KDE neon"
VERSION="5.23"
ID=neon
ID_LIKE="ubuntu debian"
PRETTY_NAME="KDE neon User - Plasma 25th Anniversary Edition"
VARIANT="User Edition"
VARIANT_ID=user
VERSION_ID="20.04"
HOME_URL="https://neon.kde.org/"
SUPPORT_URL="https://neon.kde.org/"
BUG_REPORT_URL="https://bugs.kde.org/"
LOGO=start-here-kde-neon
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
- tsfresh version: 0.19.0
- Install method (pip): ```pip install tsfresh```

*CUDA*
```# nvcc --version```
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```

but:
``` # whereis cuda```
```
cuda: /usr/lib/cuda /usr/include/cuda.h /usr/local/cuda
```

```# /usr/local/cuda/bin/nvcc --version```
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0
```

but (python):
```
>>> import torch
print(torch.version.cuda)
10.2
```
but:
```# nvidia-smi```
```
Fri Jan  7 16:05:29 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.91.03    Driver Version: 460.91.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 2070    Off  | 00000000:01:00.0  On |                  N/A |
| 27%   33C    P8     9W / 215W |    677MiB /  7981MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1329      G   /usr/lib/xorg/Xorg                224MiB |
|    0   N/A  N/A      4226      G   /usr/bin/kwin_x11                  18MiB |
|    0   N/A  N/A      4787      G   /usr/bin/plasmashell               35MiB |
|    0   N/A  N/A      5102      G   /usr/bin/ktorrent                   2MiB |
|    0   N/A  N/A      7321      G   ...AAAAAAAAA= --shared-files        7MiB |
|    0   N/A  N/A      7475      G   ...AAAAAAAAA= --shared-files      137MiB |
|    0   N/A  N/A     11298      C   ...virtualenvs/ml/bin/python      151MiB |
|    0   N/A  N/A     17620      C   ...virtualenvs/ml/bin/python       93MiB |
+-----------------------------------------------------------------------------+
```

**Comment by kempa-liehr** [comment] 2022-01-10 05:09
Hi @alekseikorobov,
 
Thanks for posting your bug report.

Extrapolating from https://github.com/numba/numba/issues/7006#issue-879314768, your error might be caused by a mismatch between your CUDA version (11.2) and Cuda compilation tool (11.5).

If this version mismatch does not cause the error, please follow up with the stumpy developer team (https://github.com/TDAmeritrade/stumpy).

I'm closing this bug report for now. Please feel free to reopen, if you find a solution or workaround, which might be useful for the tsfresh community.

Cheers,
Andreas

**Closed by kempa-liehr** 2022-01-10 05:09 UTC
Labels: bug
